### ISSUE TITLE
reCaptcha with confirmation page

### ISSUE THREAD

**Issue by ubermanu** [einpraegsam/powermailrecaptcha#1]
Hi,
When i submit a basic form, after the **confirmation page**, it gives me this error

![selection_025](https://cloud.githubusercontent.com/assets/1533514/19651537/8b80f500-9a0d-11e6-9dee-846a7134d66a.png)

Without confirmation page, everything is fine tho
**Note**: I have the same error with the `jh_captcha` extension, any idea?
Thanks

**Comment by einpraegsam** [comment]
Thx, the problem is that the validator will be checked first on confirmationAction() and then a second time on createAction(). I pushed a change to master branch for a fix. 
The bad news on this: This needs a small feature in powermail. So this will only work with the next powermail version 3.9.0.
The powermailrecaptcha version for this will be 1.1.0
